server {
    listen 8080;
    server_name argus-bt.duckdns.org;

    # Certbot ACME challenge path
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all other HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 8443 ssl;
    server_name argus-bt.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/argus-bt.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/argus-bt.duckdns.org/privkey.pem;

    # Modern SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass         http://argus-ingestion-api:8100;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
